services:
  - mysql
version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
before_build:
- cmd: >-
    source\AppVeyor\AppVeyorBeforeCompile.bat

build:
  project: source\ACE.sln
  verbosity: minimal
test: on